n = input('Digite algo: ')
print('O tipo é ', type(n))
print('É alfabetico? ', n.isalpha())
print('É número?', n.isalnum())
print('É decimal? ', n.isdecimal())
print('É lower?', n.islower())
print('Só tem espaços?', n.isspace())